name: Generate Package

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Get pnpm
              uses: pnpm/action-setup@v2
              with:
                version: 8
            - name: Build and pack extension
              run: |
                pnpm i
                pnpm build
                mkdir rabbithole
                zip -r rabbithole.zip dist
                mv dist rabbithole
            - uses: actions/upload-artifact@v3
              with:
                name: rabbithole
                path: rabbithole
            - name: Get Next Version
              id: semver
              uses: ietf-tools/semver-action@v1
              with:
                token: ${{ github.token }}
                majorList: release
                noVersionBumpBehavior: silent
            - name: Changelog
              id  : autoChangelog
              uses: ardalanamini/auto-changelog@v4
            - name: Create Release
              uses: ncipollo/release-action@v1
              with:
                tag: ${{ steps.semver.outputs.next }}
                artifacts: |
                  rabbithole.zip
                allowUpdates: true
                draft: false
                body: ${{ steps.autoChangelog.outputs.changelog }}
                token: ${{ github.token }}
