name: Test

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Get pnpm
              uses: pnpm/action-setup@v2
              with:
                version: 8
            - name: Build and pack extension
              run: |
                pnpm i
                pnpm build
                zip -r rabbithole.zip dist
            - uses: actions/upload-artifact@v3
              with:
                name: my-artifact
                path: rabbithole.zip
